// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjqfdxaobucumtlmcakw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqcWZkeGFvYnVjdW10bG1jYWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzY0OTQsImV4cCI6MjA2ODc1MjQ5NH0.WXm8WxTgg8XxBY2LRQHN02rHFEUpCIkmlA26NccJcaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});